apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: voting
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-39e67556-f9bf-400d-b99a-1925981c2d2a:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - example-voting-app
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/voting/github-39e67556-f9bf-400d-b99a-1925981c2d2a
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: github-token
        key: token
