apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  #generateName: corpsite-wf-test-
  name: corpsite-ci-test
spec:
  entrypoint: ci
  podGC:
    strategy: OnWorkflowSuccess
  volumeClaimTemplates:
  - metadata:
      name: codefresh-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  templates:
  - name: ci
    dag:
      tasks:
      - name: ci
        templateRef:
          name: corpsite-ci-wf-tplt
          template: ci-pipeline
        arguments:
          parameters:
          - name: REPO
            value: https://github.com/lrochette/CorpSite
          - name: REVISION
            value: master
          - name: SHA
            value: 46e5353d292dac9dbc1fc8c9c5c32cd2de37b8a9
