apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-workflow
spec:
  entrypoint: pipeline
  templates:
    - name: pipeline
      metadata:
      dag:
        tasks:
        - name: test1
          template: test
          arguments:
            parameters:
            - name: IMAGE
              value: bash
      - name: sync
        depends: test1
        templateRef:
          name: argo-hub.argocd.0.0.1
          template: sync
        arguments:
          parameters:
          - name: app
            value: 'color-dev'
          - name: serverUrl
            value: 'argocd-server.csdp.svc.cluster.local'

      - name: wait
        depends: sync
        templateRef:
          name: argo-hub.argocd.0.0.1
          template: wait
        arguments:
          parameters:
          - name: app
            value: 'color-dev'
          - name: flags
            value: '--health'
          - name: serverUrl
            value: 'argocd-server.csdp.svc.cluster.local'

        - name: test2
          template: test
          arguments:
            parameters:
            - name: IMAGE
              value: bash
          depends: wait



    # Test template
    - name: test
      metadata:
      inputs:
        parameters:
          - name: IMAGE
      container:
        image: '{{ inputs.parameters.IMAGE }}'
        command: [sh, -c]
        args: ["ls"]
