apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asdasdfasdfdf
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./holding
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: HEAD
  destination:
    name: lr3
    namespace: foobar
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
