apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-cc8a39d6-cf39-4123-869a-04f6142f8592:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/demo/github-cc8a39d6-cf39-4123-869a-04f6142f8592
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
