apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-f40ed178-82cc-41db-9ce3-250ecfdd99a5:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/demo2/github-f40ed178-82cc-41db-9ce3-250ecfdd99a5
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
