apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: foo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-907cb605-8ec7-4267-89f6-4143c2842315:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - CorpSite
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/foo/github-907cb605-8ec7-4267-89f6-4143c2842315
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
