# This Workflow Template is used to create your first CI pipeline in CSDP
# This CI pipeline builds a docker image using Kaniko, uploads image metadata to CSDP, and tests the image

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: foo
spec:
  arguments:
    # List here all the arguments to pass as variables to the Workflow from the Sensor
    # Use this syntax to pass them into the Workflow Templates: "{{workflow.parameters.REPO}}"
    # These are the arguments that are required for this CI pipeline:
    parameters:
      - name: REPO
      - name: BRANCH
      - name: GIT_COMMIT_URL
      - name: GIT_COMMIT_MESSAGE
      - name: CREATE_CR
        value: true
  entrypoint: ci-pipeline
  templates:
    - name: ci-pipeline
      inputs:
        parameters:
          - name: REPO
          - name: BRANCH
          - name: GIT_COMMIT_URL
            value: ''
          - name: GIT_COMMIT_MESSAGE
            value: ''
          - name: CREATE_CR
            value: true

      dag:
        tasks:

        - name: clone
          templateRef:
            name: argo-hub.git.0.0.3
            template: clone
          arguments:
            parameters:
            - name: REPO_URL
              value: "{{inputs.parameters.REPO}}"
            - name: REVISION
              value: "{{inputs.parameters.BRANCH}}"
            - name: GIT_TOKEN_SECRET
              value: github-token
          outputs:
            - artifacts:
              - name: repo
                path: /tmp/CorpSite