apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-panorays
spec:
  arguments:
    parameters:
      - name: ARGOCD_SERVER
        value: a626d6e547916477ea3cfb3866d255a0-567556894.us-east-1.elb.amazonaws.com
  entrypoint: pipeline
  templates:
    - name: pipeline
      metadata:
      dag:
        tasks:
        - name: test1
          template: test
          arguments:
            parameters:
            - name: IMAGE
              value: bash
        - name: sync
          depends: test1
          templateRef:
            name: argo-hub.argocd.0.0.1
            template: sync
          arguments:
            parameters:
            - name: app
              value: 'color-dev'
            - name: serverUrl
              value: '{{workflow.parameters.ARGOCD_SERVER}}'

        - name: wait
          depends: sync
          templateRef:
            name: argo-hub.argocd.0.0.1
            template: wait
          arguments:
            parameters:
            - name: app
              value: 'color-dev'
            - name: flags
              value: '--health'
            - name: serverUrl
              value: '{{workflow.parameters.ARGOCD_SERVER}}'

        - name: test2
          template: test
          arguments:
            parameters:
            - name: IMAGE
              value: bash
          depends: wait


    # Test template
    - name: test
      metadata:
      inputs:
        parameters:
          - name: IMAGE
      container:
        image: '{{ inputs.parameters.IMAGE }}'
        command: [sh, -c]
        args: ["ls"]
