apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: corpsite
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-corpsite-1:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - CorpSite
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/corpsite/github-corpsite-1
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
