apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-globex
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: https://github.com/lrochette/CorpSite_gitops
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
