apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: express
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    push:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/express/push
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
