apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sonar
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-e2955379-1970-4ba9-8b74-8b477a41e7cb
      eventName: github-e2955379-1970-4ba9-8b74-8b477a41e7cb
      eventSourceName: sonar
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: test
        conditions: github-e2955379-1970-4ba9-8b74-8b477a41e7cb
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sonar-test-
              spec:
                workflowTemplateRef:
                  name: sonar-test
          parameters: []
