apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: isp
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-49463ada-719b-4a77-a208-f59d8fb6cc65:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - CF-tests
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/isp/github-49463ada-719b-4a77-a208-f59d8fb6cc65
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
