apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codefresh-sa-default
  namespace: v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-sa
subjects:
  - kind: ServiceAccount
    name: default
    namespace: v2
