# This Workflow Template is used to create your first CI pipeline in CSDP
# This CI pipeline builds a docker image using Kaniko, uploads image metadata to CSDP, and tests the image

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: snow
spec:

  entrypoint: pipeline
  templates:
    - name: pipeline
      dag:
        tasks:

        - name: create-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: createcr
          arguments:
            parameters:
            - name: TOKEN
              value: codefresh-token
            - name: SN_INSTANCE
              value: "https://dev207847.service-now.com"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOGLEVEL
              value: "debug"
            - name: CR_DATA
              value: >-
                {"short_description": "Globex deployment to QA environment",
                "description": "Change for build {{workflow.uid}}.\nThis change was created by the Codefresh GitOps CI plugin",
                "justification": "My app is awesome! Please deploy ASAP",
                "cmdb_ci":"tomcat"
                }
            - name: SN_IMAGE_NAME
              value: docker.io/lrochette/argo-hub-servicenow-integration
            - name: SN_IMAGE_TAG
              value: 1.3.0-main

        - name: update-sn-cr
          depends: create-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: updatecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "https://dev207847.service-now.com"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOGLEVEL
              value: "info"
            - name: CR_DATA
              value: '{"work_notes":"Image build with tag TAG}"}'
            - name: CR_SYSID
              value: '{{ tasks.create-sn-cr.outputs.parameters.CR_SYSID}}'
            - name: SN_IMAGE_NAME
              value: docker.io/lrochette/argo-hub-servicenow-integration
            - name: SN_IMAGE_TAG
              value: 1.3.0-main

        - name: update-sn-cr-with-config-commit
          depends: update-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: updatecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "https://dev207847.service-now.com/"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOGLEVEL
              value: "info"
            - name: CR_DATA
              value: '{"work_notes":"Deployment commit 123456"}'
            - name: CR_SYSID
              value: '{{ tasks.create-sn-cr.outputs.parameters.CR_SYSID}}'
            - name: SN_IMAGE_NAME
              value: docker.io/lrochette/argo-hub-servicenow-integration
            - name: SN_IMAGE_TAG
              value: 1.3.0-main
    # Additional templates
    - name: approve
      suspend: {}
#        duration: "5m"


    - name: sleep
      inputs:
        parameters:
          - name: DURATION
            value: 60
      script:
        image: alpine:3.7
        workingDir: /tmp/lsdir
        command: [ sh ]
        source : |
         sleep {{inputs.parameters.DURATION}}
