# This Workflow Template is used to test the ServiceNow integration

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: snow
spec:
  arguments:
    parameters:
      - name: INSTANCE
        value: https://dev202099.service-now.com

  entrypoint: pipeline
  templates:
    - name: pipeline

      dag:
        tasks:

        - name: create-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: createcr
          arguments:
            parameters:
            - name: TOKEN
              value: cf-api-key
            - name: CF_RUNTIME
              value: 'csdp'
            - name: SN_INSTANCE
              value: "{{workflow.parameters.INSTANCE}}"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOG_LEVEL
              value: "debug"
            - name: CR_DATA
              value: >-
                {"short_description": "Globex deployment to QA environment",
                "description": "Change for build {{workflow.uid}}.\nThis change was created by the Codefresh GitOps CI plugin",
                "justification": "My app is awesome! Please deploy ASAP",
                "cmdb_ci":"tomcat", "assignment_group":"a715cd759f2002002920bde8132e7018"
                }
            # - name: SN_IMAGE_NAME
            #   value: docker.io/lrochette/argo-hub-servicenow-integration
            # - name: SN_IMAGE_TAG
            #   value: 1.3.0-main

        - name: wait
          template: approve
          depends: create-sn-cr

        - name: update-sn-cr
          depends: wait
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: updatecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "{{workflow.parameters.INSTANCE}}"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOG_LEVEL
              value: "info"
            - name: CR_DATA
              value: '{"work_notes":"Image build with tag TAG}"}'
            - name: CR_SYSID
              value: '{{ tasks.create-sn-cr.outputs.parameters.CR_SYSID}}'
            # - name: SN_IMAGE_NAME
            #   value: docker.io/lrochette/argo-hub-servicenow-integration
            # - name: SN_IMAGE_TAG
            #   value: 1.3.0-main

        - name: update-sn-cr-with-config-commit
          depends: update-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: updatecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "{{workflow.parameters.INSTANCE}}"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOG_LEVEL
              value: "info"
            - name: CR_DATA
              value: >-
                {"work_notes":"Deployment commit 123456",
                 "state":0,
                 "implementation_plan":"The implementation has been approved.",
                 "test_plan":"The testing suite has passed."
                }
            - name: CR_SYSID
              value: '{{ tasks.create-sn-cr.outputs.parameters.CR_SYSID}}'
            # - name: SN_IMAGE_NAME
            #   value: docker.io/lrochette/argo-hub-servicenow-integration
            # - name: SN_IMAGE_TAG
            #   value: 1.3.0-main
        - name: pause
          depends: update-sn-cr-with-config-commit
          template: sleep
          arguments:
            parameters:
            - name: DURATION
              value: 30

        - name: close-sn-cr
          depends: pause
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: closecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "{{workflow.parameters.INSTANCE}}"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOG_LEVEL
              value: "info"
            - name: CR_SYSID
              value: '{{ tasks.create-sn-cr.outputs.parameters.CR_SYSID}}'
            - name: CR_CLOSE_CODE
              value: "successful"
            - name: CR_CLOSE_NOTES
              value: "Closed automatically by Argo-Hub ServiceNow workflow template"
            # - name: SN_IMAGE_NAME
            #   value: docker.io/lrochette/argo-hub-servicenow-integration
            # - name: SN_IMAGE_TAG
            #   value: 1.3.0-main

    # Additional templates
    - name: approve
      suspend: {}
#        duration: "5m"


    - name: sleep
      inputs:
        parameters:
          - name: DURATION
            value: 60
      script:
        image: bash:5.2.26
        workingDir: /tmp/lsdir
        command: [ sh ]
        source : |
         sleep {{inputs.parameters.DURATION}}
