apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-manager
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be Secrets Manager
      region: us-east-1  # Region where the secret is.
      auth:
        # secretRef:
        #   accessKeyID:
        #     name: awssm-secret
        #     key: access-key
        #   secretAccessKey:
        #     name: awssm-secret
        #     key: secret-access-key
        jwt:
          serviceAccountRef:
            name: argocd-server
            namespace: csdp
