apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
spec:
  calendar:
    example-with-interval:
      interval: 30m
  eventBusName: codefresh-eventbus
  template:
    container:
      name: ""
      resources: {}
