apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codefresh-delivery-pipelines
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /webhooks/corpsite
            backend:
              service:
                name: corpsite-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/demo9
            backend:
              service:
                name: demo9-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
