apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: corpsite
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
      eventName: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
      eventSourceName: corpsite
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
          - path: "[body.commits.#.modified.#()#,body.commits.#.added.#()#,body.commits.#.removed.#()#]"
            type: string
            value:
              - ".*istreamPlanet/*"
  triggers:
    - template:
        name: ci
        conditions: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: corpsite-ci-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: REVISION
                      value: ''
                    - name: SHA
                      value: ''
                workflowTemplateRef:
                  name: globex-ci
                volumeClaimTemplates:
                  - metadata:
                      name: codefresh-volume
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 1Gi
          parameters:
            - dest: spec.arguments.parameters.0.value # REPO
              src:
                dependencyName: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
                dataTemplate: '{{ .Input.body.repository.clone_url }}'

            - dest: spec.arguments.parameters.1.value #REVISION
              src:
                dependencyName: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
                dataTemplate: '{{ .Input.body.ref }}'

            - dest: spec.arguments.parameters.2.value # SHA
              src:
                dependencyName: github-f7500b30-1d53-4a96-9793-5fd2c43bf9fe
                dataTemplate: '{{ .Input.body.after }}'
