apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: deloitte
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-fded4a71-6374-448f-82c4-a0bd2853feb6
      eventName: github-fded4a71-6374-448f-82c4-a0bd2853feb6
      eventSourceName: deloitte
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: push
        conditions: github-fded4a71-6374-448f-82c4-a0bd2853feb6
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: deloitte-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                workflowTemplateRef:
                  name: deloitte-ci-push
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-fded4a71-6374-448f-82c4-a0bd2853feb6
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
