apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo9
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-948e0253-386c-4ca8-a6d2-4d211cf544af
      eventName: github-948e0253-386c-4ca8-a6d2-4d211cf544af
      eventSourceName: demo9
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: push
        conditions: github-948e0253-386c-4ca8-a6d2-4d211cf544af
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo9-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
