apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo9
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-948e0253-386c-4ca8-a6d2-4d211cf544af:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/demo9/github-948e0253-386c-4ca8-a6d2-4d211cf544af
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
