apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo1
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-b043785e-5f4a-4920-9c67-fd90c557f17b:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo1/github-b043785e-5f4a-4920-9c67-fd90c557f17b
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
