apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo1
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-b043785e-5f4a-4920-9c67-fd90c557f17b
      eventName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
      eventSourceName: demo1
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
  triggers:
    - template:
        name: push
        conditions: github-b043785e-5f4a-4920-9c67-fd90c557f17b
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo1-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple-demo1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: quay.io/lrochette/service1
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: latest
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-b043785e-5f4a-4920-9c67-fd90c557f17b
                dataTemplate: '{{ .Input.body.head_commit.message }}'
