apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo3
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-3fd8b9b6-0bae-4135-a7bd-e0b5ba3f1772:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo3/github-3fd8b9b6-0bae-4135-a7bd-e0b5ba3f1772
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
