apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-65d1845c-2231-4de0-bb44-b73600ce2b49
      eventName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
      eventSourceName: demo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
  triggers:
    - template:
        name: push
        conditions: github-65d1845c-2231-4de0-bb44-b73600ce2b49
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: demo-ci
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: quay.io/lrochette/microservice
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: quay-creds
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-65d1845c-2231-4de0-bb44-b73600ce2b49
                dataTemplate: quay-config
