apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo7
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
      eventName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
      eventSourceName: demo7
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
  triggers:
    - template:
        name: ci
        conditions: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo7-ci-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: CONTEXT
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: quay.io/lrochette/microservice
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-e712f8d3-cbe2-430e-ab8b-694600856dc6
                dataTemplate: '{{ .Input.body.head_commit.message }}'
