apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo4
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-d8a7c62d-2f2a-40c0-a0d4-139c957fd762:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo4/github-d8a7c62d-2f2a-40c0-a0d4-139c957fd762
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
