apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo6
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
      eventName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
      eventSourceName: demo6
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
  triggers:
    - template:
        name: push
        conditions: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo6-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: quay.io/lrochette/microservice
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-089f86a7-8b14-4501-bdee-a9357c95bfc3
                dataTemplate: '{{ .Input.body.head_commit.message }}'
