apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo8
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-1adb87ba-14fc-4393-beb6-ae966694f678
      eventName: github-1adb87ba-14fc-4393-beb6-ae966694f678
      eventSourceName: demo8
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: anthony
        conditions: github-1adb87ba-14fc-4393-beb6-ae966694f678
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo8-anthony-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
