apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo6
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-089f86a7-8b14-4501-bdee-a9357c95bfc3:
      events:
        - push
      repositories:
        - owner: codefresh-contrib
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo6/github-089f86a7-8b14-4501-bdee-a9357c95bfc3
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
