apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
      eventName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
      eventSourceName: demo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
  triggers:
    - template:
        name: ci
        conditions: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo-ci-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: CONTEXT
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: demo-ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: quay.io/lrochette/microservice
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: .
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: registry-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-f30b9a5c-048e-4012-891d-2b236a1a5f08
                dataTemplate: docker-config
