apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo1
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-d9393fa2-bcb5-462b-82ec-bc82d590a6a9:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/demo1/github-d9393fa2-bcb5-462b-82ec-bc82d590a6a9
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
