apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-f756432c-c4e0-43e2-aa37-ad51d6b4b6cb:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - express-microservice
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo/github-f756432c-c4e0-43e2-aa37-ad51d6b4b6cb
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
