apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: echo-message
spec:
  arguments:
    parameters:
    - name: message
  entrypoint: echo
  podGC:
    strategy: OnWorkflowCompletion
  serviceAccountName: codefresh-sa
  templates:
  - container:
      args:
      - '{{inputs.parameters.message}}'
      command:
      - echo
      image: alpine
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: message
        value: hello world
    metadata: {}
    name: echo
    outputs: {}
