# This Workflow Template is used to create your first CI pipeline in CSDP
# This CI pipeline builds a docker image using Kaniko, uploads image metadata to CSDP, and tests the image
# https://codefresh.io/csdp-docs/docs/getting-started/quick-start/create-ci-pipeline/
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: isp-pipeline
spec:

  entrypoint: pipeline
  templates:
    - name: pipeline
      inputs:
        parameters:
          - name: REPO
          - name: REVISION
          - name: SHA
      dag:
        tasks:
        - name: clone
          templateRef:
            name: lr.git
            template: clone
          arguments:
            parameters:
            - name: REPO_URL
              value: "{{inputs.parameters.REPO}}"
            - name: REVISION
              value: "{{inputs.parameters.REVISION}}"
            - name: GIT_TOKEN_SECRET
              value: github-token

        - name: ls1
          template: listing
          depends: clone
          arguments:
            parameters:
              - name: DIR
                value: "{{tasks.clone.outputs.parameters.REPO_NAME}}"


    # Other templates
    - name: listing
      # requires this pod to be run on an nvidia.com/gpu labeled node
      nodeSelector:
        nvidia.com/gpu: "true"
      # allows this pod to be run on an nvidia.com/gpu tainted node
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"

      inputs:
        parameters:
          - name: DIR
            value: "."
      container:
        # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
        resources:
        # don't use requests for GPUs: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
