apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: jira-test
  annotations:
    argo-hub/version: '0.0.1'
    argo-hub/description: 'This Workflow Template is used to create your first CI pipeline in CSDP'
    argo-hub/categories: 'starter template'
    argo-hub/license: 'MIT'
    argo-hub/owner_name: 'Eti Zaguri'
    argo-hub/owner_email: 'eti.zaguri@codefresh.io'
    argo-hub/owner_avatar: 'https://avatars.githubusercontent.com/u/85868206'
    argo-hub/owner_url: 'https://github.com/eti-codefresh'
    argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/ci-simple/assets/icon.svg"
    argo-hub/icon-background: "#004C76"
spec:
#   volumes:
#     - name: docker-config
#       secret:
#         items:
#           - key: .dockerconfigjson
#             path: config.json
#         secretName: '{{ inputs.parameters.DOCKER_CONFIG_SECRET }}'
  entrypoint: create-jira
  templates:
    - name: ci-tasks
      templateRef:
        name: argo-hub.jira.0.0.1
        template: create-issue    
    #   metadata:
    #     annotations:
    #       argo-hub-template/description: 'Builds a docker image using Kaniko, uploads image metadata to CSDP, and tests the image'
    #       argo-hub-template/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/workflows/ci-simple/assets/icon.svg"
    #       argo-hub-template/icon_background: "#004C76"
      inputs:
        parameters:
          # required
          - name: JIRA_API_KEY
            value: jira-token
          - name: JIRA_BASE_URL
            value: https://codefresh-io.atlassian.net/
          - name: JIRA_USERNAME
            value: jira-token
          # optional
          - name: ACTION
            default: 'issue_create'
          - name: JIRA_API_KEY_SECRET_KEY
            default: 'token'
          - name: JIRA_USERNAME_SECRET_KEY
            default: 'email'
          - name: ISSUE_PROJECT
            default: 'FT'
          - name: ISSUE_SUMMARY
            default: 'test of Jira integration'
          - name: ISSUE_DESCRIPTION
            default: 'this is the longer description'
        #   - name: ISSUE_COMPONENTS
        #     default: ''
        #   - name: ISSUE_CUSTOMFIELDS
        #     default: ''
          - name: ISSUE_TYPE
            default: 'Bug'
    