apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    name: jira-test
    annotations:
        argo-hub/version: '0.0.1'
        argo-hub/description: 'This Workflow Template is used to create your first CI pipeline in CSDP'
        argo-hub/categories: 'starter template'
        argo-hub/license: 'MIT'
        argo-hub/owner_name: 'Eti Zaguri'
        argo-hub/owner_email: 'eti.zaguri@codefresh.io'
        argo-hub/owner_avatar: 'https://avatars.githubusercontent.com/u/85868206'
        argo-hub/owner_url: 'https://github.com/eti-codefresh'
        argo-hub/icon_url: "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/ci-simple/assets/icon.svg"
        argo-hub/icon-background: "#004C76"
spec:
    entrypoint: pipeline
    templates:
    -   name: pipeline
        dag:
            tasks:
            -   name: create-jira-issue
                templateRef:
                    name: argo-hub.jira.0.0.1
                    template: create-issue
                arguments:
                    parameters:
                    -   name: JIRA_API_KEY
                        value: jira-token
                    -   name: JIRA_BASE_URL
                        value: https://codefresh-io.atlassian.net/
                    -   name: JIRA_USERNAME
                        value: jira-token
                    -   name: JIRA_API_KEY_SECRET_KEY
                        value: 'token'
                    -   name: JIRA_USERNAME_SECRET_KEY
                        value: 'email'
                    -   name: ISSUE_PROJECT
                        value: FT
                    -   name: ISSUE_SUMMARY
                        value: this is the shorter description
                    -   name: ISSUE_DESCRIPTION
                        value: this is the longer description
                    -   name: ISSUE_TYPE
                        value: Task
            -   name: issue-transition-status
                dependencies: [create-jira-issue]
                templateRef:
                    name: argo-hub.jira.0.0.1
                    template: issue-transition-status
                arguments:
                    parameters:
                    -   name: JIRA_API_KEY
                        value: jira-token
                    -   name: JIRA_BASE_URL
                        value: https://codefresh-io.atlassian.net/
                    -   name: JIRA_USERNAME
                        value: jira-token
                    -   name: JIRA_API_KEY_SECRET_KEY
                        value: 'token'
                    -   name: JIRA_USERNAME_SECRET_KEY
                        value: 'email'
                    -   name: JIRA_ISSUE_SOURCE_FIELD
                        value: "{{tasks.create-jira-issue.outputs.parameters.JIRA_ISSUE_SOURCE_FIELD}}"
                    -   name: DESIRED_ISSUE_STATUS
                        value: 'In Progress'
                    -   name: VERBOSE
                        value: 'true'
            # -   name: update-jira-issue
            #     dependencies: [create-jira-issue]
            #     templateRef:
            #         name: argo-hub.jira.0.0.1
            #         template: update-issue
            #     arguments:
            #         parameters:
            #         -   name: JIRA_API_KEY
            #             value: jira-token
            #         -   name: JIRA_BASE_URL
            #             value: https://codefresh-io.atlassian.net/
            #         -   name: JIRA_USERNAME
            #             value: jira-token
            #         -   name: JIRA_API_KEY_SECRET_KEY
            #             value: 'token'
            #         -   name: JIRA_USERNAME_SECRET_KEY
            #             value: 'email'
            #         -   name: ISSUE_PROJECT
            #             value: FT
            #         -   name: ISSUE_SUMMARY
            #             value: this is the shorter description
            #         -   name: ISSUE_DESCRIPTION
            #             value: this is the new longer description
            #         -   name: ISSUE_TYPE
            #             value: Task
            #         -   name: JIRA_ISSUE_SOURCE_FIELD
            #             value: "{{tasks.create-jira-issue.outputs.parameters.JIRA_ISSUE_SOURCE_FIELD}}"
            # -   name: update-jira-comment
            #     dependencies: [create-jira-comment]
            #     templateRef:
            #         name: argo-hub.jira.0.0.1
            #         template: update-comment
            #     arguments:
            #         parameters:
            #         -   name: JIRA_API_KEY
            #             value: jira-token
            #         -   name: JIRA_BASE_URL
            #             value: https://codefresh-io.atlassian.net/
            #         -   name: JIRA_USERNAME
            #             value: jira-token
            #         -   name: JIRA_API_KEY_SECRET_KEY
            #             value: 'token'
            #         -   name: JIRA_USERNAME_SECRET_KEY
            #             value: 'email'
            #         -   name: JIRA_ISSUE_SOURCE_FIELD
            #             value: "{{tasks.create-jira-issue.outputs.parameters.JIRA_ISSUE_SOURCE_FIELD}}"
            #         -   name: COMMENT_BODY
            #             value: 'test of Jira integration comment new'
            #         -   name: JIRA_COMMENT_ID
            #             value: "{{tasks.create-jira-comment.outputs.parameters.JIRA_COMMENT_ID}}"
            