apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: jira
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-7ea15900-8532-433b-aabd-bec422e7f58d:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - til
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/jira/github-7ea15900-8532-433b-aabd-bec422e7f58d
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
