apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
spec:
  project: default
  source:
    path: ./
    repoURL: https://github.com/lrochette/express-microservice_gitops
    targetRevision: HEAD
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
