apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-relay-client
spec:
  selector:
    matchLabels:
      app: webhook-relay-client
  replicas: 1
  template:
    metadata:
      labels:
        app: webhook-relay-client
    spec:
      containers:
        - name: webhook-relay-client
          image: quay.io/codefresh/webhook-relay-client:1.0.8
          env:
            - name: SOURCE_URL
              # Channel name should equal the runtime name
              value: https://lrcsdp.support.cf-cd.com/subscribe/:csdp
            - name: TARGET_BASE_URL
              # All payloads will be sent to TARGET_BASE_URL/webhooks/:channel/*
              value: https://lrcsdp.support.cf-cd.com/
