apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cd-simple
spec:
  arguments:
    parameters:
      - name: ARGOCD_APP
      - name: ARGOCD_SERVER
  entrypoint: cd-steps
  onExit: slack-announce-finish

  templates:

    - name: cd-steps
      steps:
      - - name: slack-announce-start
          templateRef:
            name: argo-hub.slack.0.0.2
            template: post-to-channel
          arguments:
            parameters:
            - name: SLACK_CHANNEL
              value: "laurent.rochette@codefresh.io"
            - name: SLACK_TEXT
              value: "Starting deployment of Argo CD app '{{workflow.parameters.ARGOCD_APP}}'"
            - name: SLACK_TOKEN
              value: slack-token
      - - name: argocd-sync
          templateRef:
            name: argo-hub.argocd.0.0.1
            template: sync
          arguments:
            parameters:
            - name: app
              value: "{{workflow.parameters.ARGOCD_APP}}"
            - name: serverUrl
              value: "{{workflow.parameters.ARGOCD_SERVER}}"
            - name: flags
              value: "--insecure --plaintext"
      - - name: wait
          templateRef:
            name: argo-hub.argocd.0.0.1
            template: wait
          arguments:
            parameters:
            - name: app
              value: "{{workflow.parameters.ARGOCD_APP}}"
            - name: serverUrl
              value: "{{workflow.parameters.ARGOCD_SERVER}}"
            - name: flags
              value: '--health --insecure --plaintext'

    - name: slack-announce-finish
      steps:
      - - name: slack-announce-finish
          templateRef:
            name: argo-hub.slack.0.0.2
            template: post-to-channel
          arguments:
            parameters:
            - name: SLACK_CHANNEL
              value: "laurent.rochette@codefresh.io"
            - name: SLACK_TEXT
              value: "Finished deployment of Argo CD app '{{workflow.parameters.ARGOCD_APP}}' with status '{{workflow.status}}'"
            - name: SLACK_TOKEN
              value: slack-token
