apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: color
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
      eventName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
      eventSourceName: color
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - master
  triggers:
    - template:
        name: ci
        conditions: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: color-ci-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: color
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: https://github.com/lrochette/color-coded
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: lrochette/color
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: latest
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: github-token
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: dockerhub-creds
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
                dataTemplate: dockerhub-config
