# This Workflow Template is used to create your first CI pipeline in CSDP
# This CI pipeline builds a docker image using Kaniko, uploads image metadata to CSDP, and tests the image
# https://codefresh.io/csdp-docs/docs/getting-started/quick-start/create-ci-pipeline/
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trio-ci-simple
spec:
  volumes:
    - name: docker-config
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: '{{ inputs.parameters.DOCKER_CONFIG }}'
  entrypoint: ci-tasks
  templates:
    - name: ci-tasks
      inputs:
        parameters:
          - name: GIT_REPO_URL
          - name: IMAGE_NAME
          - name: IMAGE_TAG
            value: latest
          - name: GIT_REVISION
            value: main
          - name: GIT_BRANCH
            value: main
          - name: GIT_COMMIT_URL
            value: ''
          - name: GIT_COMMIT_MESSAGE
            value: ''
          - name: DOCKERFILE
            value: Dockerfile
          # Create git secret token and apply it to your cluster under the runtime namespace
          #   kubectl create secret generic github-token           #   --from-literal=token=$GIT_TOKEN --dry-run=client           #   --save-config -o yaml | kubectl apply -f - -n $NAMESPACE
          - name: GIT_TOKEN_SECRET
            value: github-token # the name of the git secret token you applied to your cluster
          - name: CONTEXT
            value: .
          # Create registry-creds secret and apply it to your cluster under the runtime namespace
          # You can use also use other creds such gcr/aws; please look at the template inputs for more info: https://github.com/codefresh-io/argo-hub/blob/main/workflows/codefresh-csdp/versions/0.0.6/docs/report-image-info.md
          # kubectl create secret generic registry-creds           # --from-literal=username=$USER           # --from-literal=password=$PASSWORD           # --from-literal=domain=$DOMAIN           # --dry-run=client --save-config -o yaml | kubectl apply -f - -n $NAMESPACE
          - name: REGISTRY_CREDS
            value: registry-creds  # the name of the registry-creds secret you created
          # Create a docker-registry secret with your docker credentials and apply it to your cluster under the runtime namespace
          # https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/
          - name: DOCKER_CONFIG
            value: docker-config  # the name of the registry-creds secret you created
      dag:
        tasks:
          # https://codefresh.io/argohub/workflow-template/kaniko
          - name: build-docker-image
            templateRef:
              name: argo-hub.kaniko.0.0.1
              template: build
            arguments:
              parameters:
                - name: REPO
                  value: '{{ inputs.parameters.GIT_REPO_URL }}'
                - name: REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: IMAGE_NAME
                  value: '{{ inputs.parameters.IMAGE_NAME }}'
                - name: GIT_TOKEN_SECRET
                  value: '{{ inputs.parameters.GIT_TOKEN_SECRET }}'
                - name: DOCKERFILE
                  value: '{{ inputs.parameters.DOCKERFILE }}'
                - name: CONTEXT
                  value: '{{ inputs.parameters.CONTEXT }}'
                - name: TAG
                  value: '{{ inputs.parameters.IMAGE_TAG }}'

          #  https://codefresh.io/argohub/workflow-template/codefresh-csdp
          - name: report-image-info
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: report-image-info
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}'
                - name: CF_API_KEY
                  value: codefresh-token # this secret is created as part of the runtime installation
                - name: GIT_REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: GIT_BRANCH
                  value: '{{ inputs.parameters.GIT_BRANCH }}'
                - name: GIT_COMMIT_URL
                  value: '{{ inputs.parameters.GIT_COMMIT_URL }}'
                - name: GIT_COMMIT_MESSAGE
                  value: '{{ inputs.parameters.GIT_COMMIT_MESSAGE }}'
                - name: USERNAME
                  value: '{{ inputs.parameters.REGISTRY_CREDS }}'
                - name: PASSWORD
                  value: '{{ inputs.parameters.REGISTRY_CREDS }}'
                - name: DOMAIN
                  value: '{{ inputs.parameters.REGISTRY_CREDS }}'
            depends: build-docker-image

          # https://codefresh.io/argo/hub/workflow-template/codefresh-csdp
          # create a PR that works for this
          - name: enrich-image-with-pr
            depends: report-image-info
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: image-enricher-git-info
            arguments:
              parameters:
                - name: IMAGE
                  #value: codefreshjesse/ctrlr:ad6c1c4379cdfa6716142c7a767e5d9385aed7eb
                  value: '{{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}'
                - name: BRANCH
                  value: my-branch  # has a PR on it
                  #value: '{{ inputs.parameters.GIT_BRANCH }}'
                - name: REPO
                  value: 'codefresh-contrib/example-multiservice2'
                  #value: '{{ regexReplaceAll "https?://github.com/(.*).git" .Input.body.repository.clone_url "${1}" | trim }}'
                  #value: '{{ inputs.parameters.REPO_SLUG }}'
                - name: CF_API_KEY
                  #value: codefresh-token
                  value: 'codefresh-v1-token'
                - name: GITHUB_TOKEN
                  value: 'github-token'

                # The below should be the defaults
                - name: GITHUB_TOKEN_SECRET_KEY
                  value: 'token'
                - name: CF_TOKEN_SECRET_KEY
                  value: 'token'
                - name: GITHUB_HOST
                  value: github.com

          # https://codefresh.io/argo/hub/workflow-template/codefresh-csdp
          - name: enrich-image-with-jira-ticket
            depends: report-image-info
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: image-enricher-jira-info
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}'
                - name: CF_API_KEY
                  #value: codefresh-token # this secret is created as part of the runtime installation
                  value: codefresh-v1-token
                - name: JIRA_PROJECT_PREFIX
                  value: 'KPT'
                - name: MESSAGE
                  value: 'KPT-6'
                - name: JIRA_HOST
                  value: 'cf-demo-jira.atlassian.net'
                - name: JIRA_API_TOKEN_SECRET
                  value: 'jira-creds'

          - name: test-image
            template: test
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.IMAGE_TAG }}'
            depends: "enrich-image-with-pr && enrich-image-with-jira-ticket"

    # Test template
    - name: test
      inputs:
        parameters:
          - name: IMAGE
      container:
        image: '{{ inputs.parameters.IMAGE }}'
        command: [sh, -c]
        args: ["ls"]
