apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trio-app-ci
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-4974779e-d82a-4702-96be-a88c8ed0f613
      eventName: github-4974779e-d82a-4702-96be-a88c8ed0f613
      eventSourceName: trio-app-ci
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
          - path: >-
              {body.commits.#.modified,body.commits.#.added,body.commits.#.removed}
            template: '{{ contains "\"ctrlr/" .Input }}'
            type: string
            value:
              - 'true'
    - name: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
      eventName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
      eventSourceName: trio-app-ci
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
          - path: >-
              {body.commits.#.modified,body.commits.#.added,body.commits.#.removed}
            template: '{{ contains "\"flask-ui/" .Input }}'
            type: string
            value:
              - 'true'
    - name: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
      eventName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
      eventSourceName: trio-app-ci
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
          - path: >-
              {body.commits.#.modified,body.commits.#.added,body.commits.#.removed}
            template: '{{ contains "\"buslog/" .Input }}'
            type: string
            value:
              - 'true'
  triggers:
    - template:
        name: flask-ui
        conditions: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: trio-app-ci-flask-ui-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: latest
                    - name: GIT_REVISION
                      value: main
                    - name: GIT_BRANCH
                      value: main
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: Dockerfile
                    - name: GIT_TOKEN_SECRET
                      value: github-token
                    - name: CONTEXT
                      value: .
                    - name: REGISTRY_CREDS
                      value: registry-creds
                    - name: DOCKER_CONFIG
                      value: docker-registry
                workflowTemplateRef:
                  name: trio-ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: quay.io/codefresh_sa/flask-ui
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: flask-ui
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: registry-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-66663a58-5c5d-45ef-a7b0-e74abef4a448
                dataTemplate: docker-registry
    - template:
        name: buslog
        conditions: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: trio-app-ci-buslog-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: latest
                    - name: GIT_REVISION
                      value: main
                    - name: GIT_BRANCH
                      value: main
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: Dockerfile
                    - name: GIT_TOKEN_SECRET
                      value: github-token
                    - name: CONTEXT
                      value: .
                    - name: REGISTRY_CREDS
                      value: registry-creds
                    - name: DOCKER_CONFIG
                      value: docker-registry
                workflowTemplateRef:
                  name: trio-ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: quay.io/codefresh_sa/buslog
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: buslog
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: registry-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-abebe3b3-87bd-4078-8a2c-92557d2f2d63
                dataTemplate: docker-registry
    - template:
        name: ctrlr
        conditions: github-4974779e-d82a-4702-96be-a88c8ed0f613
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: trio-app-ci-ctrlr-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: latest
                    - name: GIT_REVISION
                      value: main
                    - name: GIT_BRANCH
                      value: main
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: Dockerfile
                    - name: GIT_TOKEN_SECRET
                      value: github-token
                    - name: CONTEXT
                      value: .
                    - name: REGISTRY_CREDS
                      value: registry-creds
                    - name: DOCKER_CONFIG
                      value: docker-registry
                workflowTemplateRef:
                  name: trio-ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: quay.io/codefresh_sa/ctrlr
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: ctrlr
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: registry-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-4974779e-d82a-4702-96be-a88c8ed0f613
                dataTemplate: docker-registry
