apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: voting
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-39e67556-f9bf-400d-b99a-1925981c2d2a
      eventName: github-39e67556-f9bf-400d-b99a-1925981c2d2a
      eventSourceName: voting
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: pipeline
        conditions: github-39e67556-f9bf-400d-b99a-1925981c2d2a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: voting-app-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                workflowTemplateRef:
                  name: voting-app-pipeline
          parameters:
            # REPO_URL
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-39e67556-f9bf-400d-b99a-1925981c2d2a
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
                # IMAGE_TAG
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-39e67556-f9bf-400d-b99a-1925981c2d2a
                dataTemplate: latest
            # REVISION
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-39e67556-f9bf-400d-b99a-1925981c2d2a
                dataTemplate: '{{ .Input.body.ref }}'
