apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: voting-app-pipeline
  annotations: {}

spec:
  volumes:
    - name: docker-config
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: dockerhub-config
  entrypoint: pipeline
  templates:
    - name: pipeline
      inputs:
        parameters:
          - name: GIT_REPO_URL
            default: https://github.com/lrochette/example-voting-app
          - name: IMAGE_TAG
            default: latest
          - name: GIT_REVISION
            default: master

      dag:
        tasks:
          # https://codefresh.io/argohub/workflow-template/kaniko
          - name: build-vote-image
            templateRef:
              name: argo-hub.kaniko.0.0.1
              template: build
            arguments:
              parameters:
                - name: REPO
                  value: '{{ inputs.parameters.GIT_REPO_URL }}'
                - name: REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: IMAGE_NAME
                  value: docker.io/lrochette/vote
                - name: GIT_TOKEN_SECRET
                  value: 'github-token'
                - name: TAG
                  value: '{{ inputs.parameters.IMAGE_TAG }}'
                - name: CONTEXT
                  value: vote
          - name: build-worker-image
            templateRef:
              name: argo-hub.kaniko.0.0.1
              template: build
            arguments:
              parameters:
                - name: REPO
                  value: '{{ inputs.parameters.GIT_REPO_URL }}'
                - name: REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: IMAGE_NAME
                  value: docker.io/lrochette/worker
                - name: GIT_TOKEN_SECRET
                  value: 'github-token'
                - name: TAG
                  value: '{{ inputs.parameters.IMAGE_TAG }}'
                - name: CONTEXT
                  value: worker
          - name: build-result-image
            templateRef:
              name: argo-hub.kaniko.0.0.1
              template: build
            arguments:
              parameters:
                - name: REPO
                  value: '{{ inputs.parameters.GIT_REPO_URL }}'
                - name: REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: IMAGE_NAME
                  value: docker.io/lrochette/result
                - name: GIT_TOKEN_SECRET
                  value: 'github-token'
                - name: TAG
                  value: '{{ inputs.parameters.IMAGE_TAG }}'
                - name: CONTEXT
                  value: result
          - name: test-image
            template: test
            depends: "build-vote-image && build-worker-image && build-result-image"

    # Test template

    - name: influxdb
      daemon: true
      container:
        image: influxdb:1.2
        readinessProbe:
          httpGet:
            path: /ping
            port: "8086"
          initialDelaySeconds: 5
          timeoutSeconds: 1

    - name: influxdb-client
      inputs:
        parameters:
        - name: cmd
      container:
        image: appropriate/curl:latest
        command: ["sh", "-c"]
        args: ["{{inputs.parameters.cmd}}"]

    - name: test
      steps:
      - - name: influx
          template: influxdb
      - - name: init-database
          template: influxdb-client
          arguments:
            parameters:
            - name: cmd
              value: curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode "q=CREATE DATABASE mydb"

      - - name: s1
          template: freestyle
          arguments:
            parameters:
              - name: CMD
                value: |
                  curl --silent -G http://{{steps.influx.ip}}:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu"
                  sleep 30
                  echo s1
        - name: s2
          template: freestyle
          arguments:
            parameters:
              - name: CMD
                value: |
                  sleep 30
                  echo s2

    - name: freestyle
      inputs:
        parameters:
          - name: CMD
      script:
        image: ubuntu
        command: [/bin/bash]
        source: |
          {{inputs.parameters.CMD}}
