apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex-prod
spec:
  destination:
    namespace: globex-prod
    name: lr2
  project: globex
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: .
    repoURL: https://github.com/lrochette/csdp_applications/globex/prod
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
