apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: jira
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-7ea15900-8532-433b-aabd-bec422e7f58d
      eventName: github-7ea15900-8532-433b-aabd-bec422e7f58d
      eventSourceName: jira
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: test
        conditions: github-7ea15900-8532-433b-aabd-bec422e7f58d
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: jira-test-
              spec:
                workflowTemplateRef:
                  name: jira-test
          parameters: []
