apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: color
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-9fdd5fbc-4691-45be-bd26-ba072a5f665f:
      events:
        - push
      repositories:
        - owner: lrochette
          names:
            - color-coded
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/color/github-9fdd5fbc-4691-45be-bd26-ba072a5f665f
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
