apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex-dev
spec:
  destination:
    namespace: globex
    server: https://kubernetes.default.svc
  project: globex
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: globex/overlays/dev
    repoURL: https://github.com/lrochette/csdp_applications/globex/dev
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
